"""added exif

Revision ID: 1703d030fd2d
Revises: 1be3b8bc00d5
Create Date: 2023-07-11 02:04:05.784605

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1703d030fd2d"
down_revision = "1be3b8bc00d5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exif",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("image_width", sa.Integer(), nullable=True),
        sa.Column("image_height", sa.Integer(), nullable=True),
        sa.Column("camera_producer", sa.String(), nullable=True),
        sa.Column("camera_model", sa.String(), nullable=True),
        sa.Column("iso", sa.String(), nullable=True),
        sa.Column("datetime_original", sa.DateTime(), nullable=True),
        sa.Column("gps_latitude", sa.String(), nullable=True),
        sa.Column("gps_longitude", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_exif_camera_model"), "exif", ["camera_model"], unique=False
    )
    op.create_index(
        op.f("ix_exif_camera_producer"), "exif", ["camera_producer"], unique=False
    )
    op.add_column("file", sa.Column("exif_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_file_exif_id"), "file", ["exif_id"], unique=False)
    op.create_foreign_key("exif_id", "file", "exif", ["exif_id"], ["id"])


def downgrade() -> None:
    op.drop_constraint("exif_id", "file", type_="foreignkey")
    op.drop_index(op.f("ix_file_exif_id"), table_name="file")
    op.drop_column("file", "exif_id")
    op.drop_index(op.f("ix_exif_camera_producer"), table_name="exif")
    op.drop_index(op.f("ix_exif_camera_model"), table_name="exif")
    op.drop_table("exif")
